# Generated by Django 4.2.13 on 2024-06-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='teams/images')),
                ('url', models.URLField(blank=True)),
                ('group', models.CharField(blank=True, max_length=10, null=True)),
                ('squad', models.TextField(blank=True, null=True)),
                ('qualifying', models.CharField(blank=True, max_length=100, null=True)),
                ('euro_best', models.CharField(blank=True, max_length=100, null=True)),
                ('coach', models.CharField(max_length=30)),
                ('key_player', models.CharField(blank=True, max_length=30, null=True)),
                ('did_you_know', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
